<?php

namespace SoireeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SoireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoireeRepository extends EntityRepository
{
}
